name: Code Quality Check Feature

on:
  # to fix comment : Runs on pull request targeting any branch except the default branch main
  pull_request:
    types: [ opened, synchronize, reopened]
  push:
    branches: [ feature/*, feat/*, fix/* ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.SPRING_BOOT_ASYNCHRONOUS_API_FLY_API_TOKEN }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  analyze_code:
    name: Analyze Code Quality
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

        # Set up the Java Development Kit (JDK) version 19
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19

      # Cache Sonar packages to speed up the build process
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache Maven packages to speed up the build process
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and analyze the code using Maven and SonarCloud
      - name: Analyze Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [[ ${{ github.actor }} == 'dependabot[bot]' ]]; then
            mvn -B test
          else
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Raouf25_spring-boot-asynchronous-api
          fi

  deploy:
    environment:
      name: dev-swagger-ui
      url: https://spring-boot-asynchronous-api.fly.dev/swagger-ui/index.html
    name: Deploy app
    needs: analyze_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only

  non_regression_test:
    name: Non Regression Test
    environment:
      name: dev-karate-report
      url: ${{ steps.deployment.outputs.page_url }}karate-summary.html
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

        # Set up the Java Development Kit (JDK) version 19
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      # Cache Maven packages to speed up the build process
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Non Regression Test
      - name: Non Regression Test
        continue-on-error: true
        run: |
          mvn clean test  --f ./nrt/pom.xml -PflyServer -Dapi.url='https://spring-boot-asynchronous-api.fly.dev' 

      # Create a "doc" directory and move karate reports to it
      - name: Get report
        run: |
          mkdir -p doc
          mv ./nrt/target/karate-reports/* ./doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './doc'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
