name: Release Project 2

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow bump_version
permissions:
  contents: write

env:
  POM_PATH: ${{ github.workspace }}

jobs:
  # check:   https://dev.to/shayki5/github-action-for-building-maven-project-with-docker-and-push-it-docker-hub-3c3k
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis relevance

      - name: Bump jar version
        id: bump
        run: |
          OLD_VERSION=$(cd $POM_PATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # Extracting major, minor, and build versions
          IFS='.' read -ra parts <<< "$OLD_VERSION"
          major="${parts[0]}"
          minor="${parts[1]}"
          build_version=$((parts[2] + 1))
          
          NEW_VERSION="${major}.${minor}.${build_version}"
          
          echo "Updating pom.xml at $POM_PATH from $OLD_VERSION to $NEW_VERSION"
          
          # Bump the version in the pom.xml file
          mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POM_PATH/pom.xml
          
          # Commit the changes
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          git add $POM_PATH/pom.xml
          git commit -m "chore: bump jar version from $OLD_VERSION to $NEW_VERSION"
          git push origin HEAD:production


          echo "Updating pom.xml at $POM_PATH from $OLD_VERSION to $NEW_VERSION-SNAPSHOT" for the main branch
          git fetch
          git checkout main
          # Bump the version in the pom.xml file for the next release in main
          mvn -q versions:set -DnewVersion="${NEW_VERSION}-SNAPSHOT" --file $POM_PATH/pom.xml
          git add $POM_PATH/pom.xml
          git commit -m "chore: bump jar version from $OLD_VERSION to $NEW_VERSION-SNAPSHOT"
          git push -f origin main
